# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Homelab
copyright: Copyright &copy; 2025

repo_url: https://github.com/candradebh/homelab2025

theme:
  favicon: https://github.com/candradebh/homelab2025/favicon
  name: material
  palette:
    primary: black
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - search.highlight
    - search.share

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - def_list
  - pymdownx.tasklist:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Installation:
    - installation/architecture.md
