- name: Executando no master alguns comandos
  hosts: server
  tasks:
    - name: Criar diretório se não existir
      ansible.builtin.file:
        path: "{{ path_project_master_node }}"
        state: directory
        mode: '0777'
        owner: "{{ ansible_user | default('root') }}"
        group: "{{ ansible_user | default('root') }}"


    - name: Sincronizar projeto do host local para o nó master
      ansible.posix.synchronize:
        src: "../../"
        dest: "{{ path_project_master_node }}"
        recursive: yes
        delete: no
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.idea/"
          - "--exclude=.DS_Store"
          - "--exclude=__pycache__"
          - "--exclude=k3s-ansible/"
          - "--exclude=ProxmoxVE/"
      delegate_to: localhost
      run_once: true

    - name: Executar nix develop no master1
      when: inventory_hostname == groups['server'][0]
      ansible.builtin.shell: |
        nix develop
      args:
        chdir: "{{ path_project_master_node }}"

    - name: Instalar o cillium
      when: inventory_hostname == groups['server'][0]
      ansible.builtin.shell: |
        make cilium
      args:
        chdir: "{{ path_project_master_node }}"

    - name: Executar make external no master1
      when: inventory_hostname == groups['server'][0]
      ansible.builtin.shell: |
        make external
      args:
        chdir: "{{ path_project_master_node }}"

    - name: Executar make system no master1
      when: inventory_hostname == groups['server'][0]
      ansible.builtin.shell: |
        make system
      args:
        chdir: "{{ path_project_master_node }}"


