# roles/nix/meta/main.yml
---
galaxy_info:
  role_name: nix
  author: Carlos
  description: "Instala o Nix multi‑usuário via Ansible"
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: all
    - name: Debian
      versions: all
    - name: Ubuntu
      versions: all
