- name: Selecionar o nó mestre principal
  set_fact:
    kubeconfig_source_ip: "{{ groups['server'][0] }}"
  when: groups['server'] is defined and groups['server'] | length > 0

- name: Copiar kubeconfig do nó mestre
  fetch:
    src: "{{ kubeconfig_remote_path }}"
    dest: "./{{ kubeconfig_local_path }}"
    flat: true
  delegate_to: "{{ kubeconfig_source_ip }}"
  run_once: true

- name: Substituir 127.0.0.1 pelo IP do nó remoto
  replace:
    path: "./{{ kubeconfig_local_path }}"
    regexp: 'https://127\.0\.0\.1:6443'
    replace: "https://{{ kubeconfig_source_ip }}:6443"
