# roles/nix/tasks/main.yml
---

- name: Download Nix installer
  get_url:
    url: "https://releases.nixos.org/nix/nix-{{ nix_version }}/install"
    dest: /tmp/install-nix
    mode: '0755'
  register: installer

- name: Verify installer checksum
  ansible.builtin.command:
    cmd: "sha256sum /tmp/install-nix"
  register: sum
  failed_when: installer_checksum is defined and sum.stdout.split()[0] != installer_checksum
  when: installer_checksum is defined

- name: Run Nix installer (multi-user)
  ansible.builtin.command:
    cmd: "/tmp/install-nix --daemon"
  become: true
  args:
    creates: /nix

- name: Ensure Nix daemon is enabled and running
  ansible.builtin.service:
    name: nix-daemon
    state: started
    enabled: true

- name: (Opcional) Executar comandos com nix
  ansible.builtin.shell: "{{ item }}"
  loop: "{{ nix_commands | default([]) }}"
  environment:
    USER: "{{ ansible_user }}"
    NIX_PATH: "/nix/var/nix/profiles/default"
  become: false

